# Generated by Django 5.0.1 on 2024-01-16 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_tracker_calories_alter_tracker_carbs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracker',
            name='calories',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='carbs',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='fat',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='protein',
            field=models.FloatField(default='0'),
        ),
    ]
